### PR TITLE
Add aarch64

### PR DESCRIPTION
**Pull request by enriqueartal**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)

Try to add aarch64

### CODE REVIEW

**Comment by enriqueartal** [comment]
I could not add aarch64, should I remove this PR?

**Comment by enriqueartal** [comment]
I did another try with conda-smithy, but apparently new architectures do not appear

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by enriqueartal** [comment]
Thanks!

**Pull request merged**
